#PRÁCTICA 10 FICHEROS ALBERTO ANTONIO HERNÁNDEZ HERNÁNDEZ

CPP = g++
FLAGS = -Wall -std=c++14
OBJ = alphabetic_order.cc functions_alphabetic.cc

alphabetic_order: alphabetic_order.o 
	$(CPP) $(FLAGS) $(OBJ) -o alphabetic_order 

clean:
	rm alphabetic_order.o 
	rm alphabetic_order