#PRÁCTICA 10 FICHEROS ALBERTO ANTONIO HERNÁNDEZ HERNÁNDEZ

CPP = g++
FLAGS = -Wall -std=c++14
OBJ = delete_blank_lines.cc functions.cc

delete_blank_lines: delete_blank_lines.o 
	$(CPP) $(FLAGS) $(OBJ) -o delete_blank_lines 

clean:
	rm delete_blank_lines.o 
	rm delete_blank_lines