#PRÁCTICA 10 FICHEROS ALBERTO ANTONIO HERNÁNDEZ HERNÁNDEZ

CPP = g++
FLAGS = -Wall -std=c++14
OBJ = my_cpp.cc functions.cc

my_cpp: my_cpp.o 
	$(CPP) $(FLAGS) $(OBJ) -o my_cpp 

clean:
	rm my_cpp.o 
	rm my_cpp