#PRÁCTICA 10 FICHEROS ALBERTO ANTONIO HERNÁNDEZ HERNÁNDEZ

CPP = g++
FLAGS = -Wall -std=c++14
OBJ = most_vowels.cc functions_most_vowels.cc

most_vowels: most_vowels.o 
	$(CPP) $(FLAGS) $(OBJ) -o most_vowels 

clean:
	rm most_vowels.o 
	rm most_vowels
	rm most_vowels.txt