#PRÁCTICA 10 FICHEROS ALBERTO ANTONIO HERNÁNDEZ HERNÁNDEZ

CPP = g++
FLAGS = -Wall -std=c++14
OBJ = caesar_cypher.cc functions_caesar.cc

caesar_cypher: caesar_cypher.o 
	$(CPP) $(FLAGS) $(OBJ) -o caesar_cypher 

clean:
	rm caesar_cypher.o 
	rm caesar_cypher