#PRÁCTICA 10 FICHEROS ALBERTO ANTONIO HERNÁNDEZ HERNÁNDEZ

CPP = g++
FLAGS = -Wall -std=c++14
OBJ = line_number.cc functions.cc

line_number: line_number.o 
	$(CPP) $(FLAGS) $(OBJ) -o line_number 

clean:
	rm line_number.o 
	rm line_number