#PRÁCTICA 10 FICHEROS ALBERTO ANTONIO HERNÁNDEZ HERNÁNDEZ

CPP = g++
FLAGS = -Wall -std=c++14
OBJ = rotate_vowels.cc functions.cc

rotate_vowels: rotate_vowels.o 
	$(CPP) $(FLAGS) $(OBJ) -o rotate_vowels 

clean:
	rm rotate_vowels.o 
	rm rotate_vowels