#PRÁCTICA 10 FICHEROS ALBERTO ANTONIO HERNÁNDEZ HERNÁNDEZ

CPP = g++
FLAGS = -Wall -std=c++14
OBJ = my_diff.cc functions_my_diff.cc

my_diff: my_diff.o 
	$(CPP) $(FLAGS) $(OBJ) -o my_diff 

clean:
	rm my_diff.o 
	rm my_diff