#PRÁCTICA 10 FICHEROS ALBERTO ANTONIO HERNÁNDEZ HERNÁNDEZ

CPP = g++
FLAGS = -Wall -std=c++14
OBJ = vowels_consonants.cc functions.cc

vowels_consonants: vowels_consonants.o 
	$(CPP) $(FLAGS) $(OBJ) -o vowels_consonants 

clean:
	rm vowels_consonants.o 
	rm vowels_consonants