#PRÁCTICA 10 FICHEROS ALBERTO ANTONIO HERNÁNDEZ HERNÁNDEZ

CPP = g++
FLAGS = -Wall -std=c++14
OBJ = criptography.cc functions_criptography.cc

criptography: criptography.o 
	$(CPP) $(FLAGS) $(OBJ) -o criptography 

clean:
	rm criptography.o 
	rm criptography