#PRÁCTICA 10 FICHEROS ALBERTO ANTONIO HERNÁNDEZ HERNÁNDEZ

CPP = g++
FLAGS = -Wall -std=c++14
OBJ = read_dfa.cc dfa.cc

read_dfa: read_dfa.o 
	$(CPP) $(FLAGS) $(OBJ) -o read_dfa 

clean:
	rm read_dfa.o 
	rm read_dfa